# Generated by Django 5.2.4 on 2025-08-05 21:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del artículo', max_length=50)),
                ('codigo', models.CharField(help_text='Código único del artículo', max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción del artículo', max_length=128, null=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del artículo', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['nombre', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ArticuloHistorial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_articulo_historial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del artículo', max_length=50)),
                ('codigo', models.CharField(help_text='Código único del artículo', max_length=50)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción del artículo', max_length=128, null=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del artículo', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_core.articulo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('es_venta', models.BooleanField(default=False)),
                ('transferencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_transferencia', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0, help_text='Cantidad de stock')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='shop_core.articulo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de venta', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_core.movimiento')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_core.stock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
