# Generated by Django 5.2.4 on 2025-08-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='es_deposito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='es_transferencia',
            field=models.BooleanField(default=False),
        ),
    ]
